Update Russian language
rwmt/Multiplayer pull request #225
Opened 2021-08-02 20:58 UTC by SijyKijy

Update #15

* Upgrading to the current version
* Correcting typos

2021-08-04 02:32 UTC, MEXAHOTABOP requested changes

2021-08-04 02:32 UTC, MEXAHOTABOP commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpSyncModConfigsDesc>Заставляет клиентов загружать те же конфигурации модов, что и хост; уменьшает десинхронизацию</MpSyncModConfigsDesc>
In original `reduces desyncs` with can be translated as `уменьшает количество десинхронизаций`

2021-08-04 02:32 UTC, MEXAHOTABOP commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpRestoreLastConfigs>Сбросить последнюю конфигурацию</MpRestoreLastConfigs>
I don't know context, but in English here is `Restore`, why you used word `Сбросить`(drop) instead of `Восстановить`?

2021-08-04 02:32 UTC, MEXAHOTABOP commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpChangeUsernameInfo>Вы можете изменить имя пользователя.</MpChangeUsernameInfo>
In original `You can change your username in the mod settings`
You missed part about where this can be done
must be `Вы можете изменить имя пользователя в настройках мода`

2021-08-04 02:32 UTC, MEXAHOTABOP commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpReplayOutdatedDesc3>Возможные несовместимости указаны на github.</MpReplayOutdatedDesc3>
Probably then `в релизах на github` or somehow else play around this, if you want change this.

2021-08-04 02:32 UTC, MEXAHOTABOP commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpAutosaveEvery>Автосохранение каждого</MpAutosaveEvery>
must be `каждые` since this is part of `Автосохранение каждые X дней`

2021-08-04 02:32 UTC, MEXAHOTABOP commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpArbiterDesc>Игра, которая запускается в трее и помогает в обнаружении/решении проблемы с десинхронизацией.</MpArbiterDesc>
instead of `в трее`, must be ` в фоне`

2021-08-04 02:32 UTC, MEXAHOTABOP commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpArbiterDesc>Игра, которая запускается в трее и помогает в обнаружении/решении проблемы с десинхронизацией.</MpArbiterDesc>
Probably will be better  `Копия игры которая запускается в фоне и помогает в обноружении/решении проблем с десинхронизацией`

2021-08-04 02:32 UTC, MEXAHOTABOP commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpPauseAutosaveCounter>Приостановить счетчик автосохранения</MpPauseAutosaveCounter>
I think `Counter` in original used as synonym for timer

2021-08-04 06:07 UTC, SijyKijy commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpSyncModConfigsDesc>Заставляет клиентов загружать те же конфигурации модов, что и хост; уменьшает десинхронизацию</MpSyncModConfigsDesc>
`количество десинхронизаций` sounds strange. Are desyncs measured in quantity?

2021-08-04 06:19 UTC, SijyKijy commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpRestoreLastConfigs>Сбросить последнюю конфигурацию</MpRestoreLastConfigs>
Yep, my bad

2021-08-04 10:09 UTC, MEXAHOTABOP requested changes

2021-08-04 10:09 UTC, MEXAHOTABOP commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpWrongMultiplayerVersionInfo>Сервер размещен в многопользовательской игре {0} (протокол {1}).</MpWrongMultiplayerVersionInfo>
In original `Multiplayer` mean this mod version

2021-08-04 11:02 UTC, SijyKijy commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpWrongMultiplayerVersionInfo>Сервер размещен в многопользовательской игре {0} (протокол {1}).</MpWrongMultiplayerVersionInfo>
Maybe replace `мультиплеер` with `Multiplayer` because it's a mod name?

2021-08-04 11:34 UTC, MEXAHOTABOP commented on Languages/Russian/Keyed/Multiplayer.xml
> +  <MpWrongMultiplayerVersionInfo>Сервер размещен в многопользовательской игре {0} (протокол {1}).</MpWrongMultiplayerVersionInfo>
I`m not entirely sure, but i think in this case Multiplayer is proper noun, so should be untranslated. 
I think must be something like `Сервер использует Мультиплеер версии {0} (протокол {1}).`

2021-08-04 13:29 UTC, MEXAHOTABOP approved these changes
Good job.

2021-08-18 20:24 UTC, Zetrith commented
Thanks for the pr. We've moved language data to a separate repository: https://github.com/rwmt/Multiplayer-Locale
Also, sorry, but we don't accept translations for versions in development. Please wait for a stable release.

2021-08-18 20:24 UTC, closed without merging